#!/usr/bin/env python
import sys
##from k40_whisperer import Application
import tkinter.messagebox

from Notifications_Emailer import NotificationsEmailer 

VERSION = sys.version_info[0]

class NotificationsManager:

    def __init__(self, _k40):
        self.k40 = _k40
        self.email_notif_handler = NotificationsEmailer(self.k40.NotifySmtpServer.get(), self.k40.NotifySmtpPort.get(), self.k40.NotifyEmailFrom.get(), self.k40.NotifyEmailTo.get(), self.k40.notifications_smtp_auth.get(), self.k40.NotifySmtpAuthUsername.get(), self.k40.NotifySmtpAuthPassword.get(), self.k40.NotifyEmailSubject.get())

##notifications_email
    def doNotify(self, event_enabled_flag, event_name, event_status, event_message):

        if self.k40.notifications_email.get() and event_enabled_flag.get(): ##if email notifications are enabled
            self.email_notif_handler.send_email("Event: " + event_name, event_name + ": " + event_status + "\n" + event_message  + "\n\nThis notification was generated by K40 whisperer.")
            